sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "cd data"
  - "git clone https://github.com/ludobox/borgia-le-jeu-malsain"
  - "cd .."
  - "cd client"
  - "npm install"
  - "cd .."
# command to run tests
script:
  - "ludobox serve &" # lauch a ludobox server in the background
  - "py.test tests"
  - "killall ludobox" # kill all processes at the end
  - "cd client"
  - "npm test"
