sudo: false
language: python
python:
  - "2.7"
install:
  - "cd server"
  - "python setup.py install"
  - "cd .."
  - "cd data"
  - "git clone https://github.com/ludobox/borgia-le-jeu-malsain-fr"
  - "cd .."
  - "cp config.yml.sample config.yml"
  - "python ./bin/migrations/init_db.py"
# command to run tests
script:
  - "ludobox start &" # lauch a ludobox server in the background
  - "ludobox test"
  - "killall ludobox" # kill all processes at the end
