# config file for your Ludobox

ludobox_name : "My LudoBox"
port: 8080 # the port to serve the interface (default to 8080)


# Update settings
update_mode : web # you can select 'dat' or 'web'
web_server_url : http://localhost:4040 # if you have chosen 'web', this is where the update will come from

# Directory to store all downloaded data -- default to ./data
# data_dir : /home/$USER/ludobox/data

# enable/disable creation of new games on the box
upload_allowed : true
