# config file for your Ludobox

ludobox_name : "My Great Box"
port: 8080 # the port to serve the interface (default to 8080)


# Update settings
update_mode : web # you can select 'dat' or 'web'
web_server_url : http://localhost:8080 # if you have chosen 'web', this is where the update will come from
data_dir : /home/clemsos/ludobox/test/data # default to ./data
