site_name: Ludobox Docs

pages:
    - Home: index.md
    - Installation: install.md
    - Get Started : get-started.md
    - Config : config.md
    - Devices :
      - Raspberry Pi : rpi.md
    - Architecture : architecture.md
    - Developement : dev.md
    - API Reference : api.md
    - About: about.md
    # - Contribute : contribute.md
    # - About: about.md

theme: readthedocs
