site_name: Ludobox Docs

pages:
    - Home: index.md
    - Get Started :
      - Installation: install.md
      - First Steps : get-started.md
      - Using Your Ludobox : using.md
    - For Developers :
      - Contribute  : dev.md
      - API Reference : api.md
    - About: about.md
    # - Contribute : contribute.md
    # - About: about.md

theme: readthedocs
