site_name: Ludobox Docs

pages:
    - Home: index.md
    - Installation: install.md
    - Get Started : get-started.md
    - Using Ludobox : using.md
    - For Developers: dev.md
    - About: about.md
    # - Contribute : contribute.md
    # - About: about.md

theme: readthedocs
